Feature/reset
UniGameTeam/UniGame.GameFlow pull request #7
Opened 2021-03-24 15:36 UTC by Glongooo

2021-03-26 11:44 UTC, HartMagic commented on GameFlow/Runtime/Commands/RegisterDataSourceCommand.cs
> +            asset.AddTo(lifeTime);
два раза привязка к лайфтайму

2021-03-26 11:44 UTC, HartMagic commented on GameFlow/Runtime/Commands/RegisterDataSourceCommand.cs
> -                GameLog.LogError($"NULL asset loaded from {_resource}");
загрузили, он не подошел, и не выгрузили, будет висеть в памяти пока лайфтайм не помрет и при этом никем не использоваться

2021-03-26 12:00 UTC, Mefodei requested changes

2021-03-26 12:00 UTC, Mefodei commented on GameFlow/Runtime/Commands/RegisterDataSourceCommand.cs
> +            asset.AddTo(lifeTime);
Это обновление сильно усложняет работу с сорсами, я понимаю цель изменения. Какие проблемы я вижу:
1. Несколько регистрируются как владельцы одного ресурса
2. Уже нельзя просто расшарить один сорс на несколько контейнеров, потому что есть риск что его прибьют
3. Намного больше нужно держать в голове по связям между сорсами

2021-03-30 13:12 UTC, Mefodei approved these changes

2021-03-30 13:12 UTC, merged